/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SentimentosIndexRouteImport } from './routes/sentimentos/index'
import { Route as SentimentosCriarRouteImport } from './routes/sentimentos/criar'
import { Route as SentimentosDataRegistroEditarRouteImport } from './routes/sentimentos/$dataRegistro.editar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SentimentosIndexRoute = SentimentosIndexRouteImport.update({
  id: '/sentimentos/',
  path: '/sentimentos/',
  getParentRoute: () => rootRouteImport,
} as any)
const SentimentosCriarRoute = SentimentosCriarRouteImport.update({
  id: '/sentimentos/criar',
  path: '/sentimentos/criar',
  getParentRoute: () => rootRouteImport,
} as any)
const SentimentosDataRegistroEditarRoute =
  SentimentosDataRegistroEditarRouteImport.update({
    id: '/sentimentos/$dataRegistro/editar',
    path: '/sentimentos/$dataRegistro/editar',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sentimentos/criar': typeof SentimentosCriarRoute
  '/sentimentos/': typeof SentimentosIndexRoute
  '/sentimentos/$dataRegistro/editar': typeof SentimentosDataRegistroEditarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sentimentos/criar': typeof SentimentosCriarRoute
  '/sentimentos': typeof SentimentosIndexRoute
  '/sentimentos/$dataRegistro/editar': typeof SentimentosDataRegistroEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sentimentos/criar': typeof SentimentosCriarRoute
  '/sentimentos/': typeof SentimentosIndexRoute
  '/sentimentos/$dataRegistro/editar': typeof SentimentosDataRegistroEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sentimentos/criar'
    | '/sentimentos/'
    | '/sentimentos/$dataRegistro/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sentimentos/criar'
    | '/sentimentos'
    | '/sentimentos/$dataRegistro/editar'
  id:
    | '__root__'
    | '/'
    | '/sentimentos/criar'
    | '/sentimentos/'
    | '/sentimentos/$dataRegistro/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SentimentosCriarRoute: typeof SentimentosCriarRoute
  SentimentosIndexRoute: typeof SentimentosIndexRoute
  SentimentosDataRegistroEditarRoute: typeof SentimentosDataRegistroEditarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sentimentos/': {
      id: '/sentimentos/'
      path: '/sentimentos'
      fullPath: '/sentimentos/'
      preLoaderRoute: typeof SentimentosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sentimentos/criar': {
      id: '/sentimentos/criar'
      path: '/sentimentos/criar'
      fullPath: '/sentimentos/criar'
      preLoaderRoute: typeof SentimentosCriarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sentimentos/$dataRegistro/editar': {
      id: '/sentimentos/$dataRegistro/editar'
      path: '/sentimentos/$dataRegistro/editar'
      fullPath: '/sentimentos/$dataRegistro/editar'
      preLoaderRoute: typeof SentimentosDataRegistroEditarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SentimentosCriarRoute: SentimentosCriarRoute,
  SentimentosIndexRoute: SentimentosIndexRoute,
  SentimentosDataRegistroEditarRoute: SentimentosDataRegistroEditarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
